import {env,waitUntil} from 'cloudflare:workers';
import {officialMenuProducts} from '../../../lib/menu-data';
import {staffReport,ReportInputError} from '../../../lib/staff-reports';
const rt=()=>env as unknown as {DB:D1Database,BUCKET:R2Bucket,TELEGRAM_BOT_TOKEN?:string,TELEGRAM_ORDERS_CHAT_ID?:string,NOTIFICATION_JOB_SECRET?:string};
const out=(d:unknown,s=200)=>Response.json(d,{status:s,headers:{'Cache-Control':'no-store'}});
const telegramOwners=['tg:5850652180'];
const telegramBotIds=['8772857082','8931760260'];
const defaults={address:'Москва, ул. Барклая, 6',accepting:false,deliveryEnabled:false,fee:0,minimum:0,zone:'',staffBotId:'8931760260',staff:[] as string[],owners:[] as string[]};
async function read(id:string){const r=await rt().DB.prepare('SELECT data FROM records WHERE id=?').bind(id).first<{data:string}>();return r?JSON.parse(r.data):null;}
async function put(id:string,kind:string,owner:string,data:unknown){await rt().DB.prepare('INSERT INTO records (id,kind,owner,data,created) VALUES (?,?,?,?,?) ON CONFLICT(id) DO UPDATE SET data=excluded.data').bind(id,kind,owner,JSON.stringify(data),Date.now()).run();}
async function ensureOfficialProducts(){
 // Initialization must never overwrite changes made by the café.
 const marker='seed:official-menu-v4';if(await read(marker))return;
 const owner=telegramOwners[0],created=Date.now();
 for(let i=0;i<officialMenuProducts.length;i+=40)await rt().DB.batch(officialMenuProducts.slice(i,i+40).map(p=>rt().DB.prepare('INSERT INTO records (id,kind,owner,data,created) VALUES (?,?,?,?,?) ON CONFLICT(id) DO NOTHING').bind('product:'+p.id,'product',owner,JSON.stringify(p),created)));
 await rt().DB.prepare('INSERT INTO records (id,kind,owner,data,created) VALUES (?,?,?,?,?) ON CONFLICT(id) DO NOTHING').bind(marker,'seed',owner,JSON.stringify({completed:true}),created).run();
}
// Explicit one-time reopening requested by the owner on 2026-09-28.
// The marker and setting are committed together; subsequent STOP is never undone.
async function applyRequestedOpening(){
 const marker='operation:open-orders-20260928';
 if(await read(marker))return;
 await rt().DB.batch([
 rt().DB.prepare(`INSERT INTO records(id,kind,owner,data,created)
 SELECT 'settings','settings',?,?,? WHERE NOT EXISTS(SELECT 1 FROM records WHERE id=?)
 ON CONFLICT(id) DO UPDATE SET data=json_set(records.data,'$.accepting',json('true'))`).bind(telegramOwners[0],JSON.stringify({...defaults,accepting:true}),Date.now(),marker),
 rt().DB.prepare('INSERT INTO records(id,kind,owner,data,created) VALUES (?,?,?,?,?) ON CONFLICT(id) DO NOTHING').bind(marker,'operation',telegramOwners[0],JSON.stringify({completed:true}),Date.now())]);
}
const categoryNames=['Все','Завтраки','Салаты','Супы','Блюда из теста','Хинкал','Вторые блюда','Шашлыки','Мангал','Гарниры','Рыба','Хлеб и соусы','Чайная карта'];
const categorySlugs=['all','breakfast','salads','soups','dough','khinkal','mains','skewers','grill','sides','fish','bread','tea'];
function canonicalProduct(p:any){const cat=/хинкал/i.test(p.name)||/^(хинкал|хинкалы)$/i.test(p.cat)?'Хинкал':/^салаты( и закуски)?$/i.test(p.cat)?'Салаты':p.cat;return {...p,cat};}
async function catalog(){await ensureOfficialProducts();const rows=await rt().DB.prepare("SELECT data FROM records WHERE kind='product'").all<{data:string}>();const order=new Map(officialMenuProducts.map((p,i)=>[p.id,i]));return rows.results.map(r=>canonicalProduct(JSON.parse(r.data))).filter(p=>!p.hidden).map(p=>({...p,trackStock:!!p.trackStock,stock:Number.isInteger(p.stock)?p.stock:0,available:p.available!==false&&(!p.trackStock||p.stock>0)})).sort((a,b)=>(order.get(a.id)??10000)-(order.get(b.id)??10000)||a.name.localeCompare(b.name,'ru'));}
function categoryMetadata(products:any[]){const present=new Set(products.map(p=>p.cat));return [...categoryNames.filter(n=>n==='Все'||present.has(n)),...[...present].filter(n=>!categoryNames.includes(n)).sort()].map(name=>({name,image:'/category-art/'+(categorySlugs[categoryNames.indexOf(name)]||'all')+'.webp'}));}
function deliveryFields(body:any){
 if(body.delivery==='pickup')return {details:null,address:'',fields:{}};
 const d=body.deliveryDetails,fields:Record<string,string>={};
 if(!d||!['mall','house'].includes(d.type))return{details:null,address:'',fields:{type:'Выберите ТЦ или Дом'}};
 const required=d.type==='mall'?['mall','pavilion','street','house']:['street','house'];
 const optional=d.type==='house'?['apartment','entrance','floor','intercom']:[];
 const labels:Record<string,string>={mall:'Название ТЦ',pavilion:'Номер павильона',street:'Улица',house:'Номер дома',apartment:'Квартира/офис',entrance:'Подъезд',floor:'Этаж',intercom:'Домофон'};
 const details:Record<string,string>={type:d.type};
 for(const k of [...required,...optional]){const v=typeof d[k]==='string'?d[k].trim():'';if(required.includes(k)&&!v)fields[k]='Заполните поле «'+labels[k]+'»';if(v.length>120)fields[k]='Не более 120 символов';if(v)details[k]=v;}
 const address=(d.type==='mall'?'ТЦ «'+(details.mall||'')+'», павильон '+(details.pavilion||'')+', ':'')+'ул. '+(details.street||'')+', дом '+(details.house||'')+optional.filter(k=>details[k]).map(k=>', '+labels[k]+': '+details[k]).join('');
 return{details,address,fields};
}
function notificationsConfigured(){return !!rt().TELEGRAM_BOT_TOKEN&&/^-?[0-9]+$/.test(rt().TELEGRAM_ORDERS_CHAT_ID||'');}
async function notificationState(){const rows=await rt().DB.prepare("SELECT json_extract(data,'$.status') AS status,count(*) AS n FROM records WHERE kind='notification' GROUP BY json_extract(data,'$.status')").all<{status:string,n:number}>();return{configured:notificationsConfigured(),pending:rows.results.filter(r=>['pending','sending'].includes(r.status)).reduce((n,r)=>n+r.n,0),uncertain:rows.results.find(r=>r.status==='uncertain')?.n||0};}
function notificationText(o:any,id:string){return ['Заказ № '+(o.number||id),o.source==='counter'?'Источник: Касса':'Источник: Мини-приложение',...o.items.map((i:any)=>i.name+' × '+i.quantity+' — '+i.price*i.quantity+' ₽'),'Итого: '+o.total+' ₽',o.delivery==='counter'?'Заказ у кассы':o.delivery==='pickup'?'Самовывоз':'Доставка',o.name||'',o.phone||'',o.address||'',(o.payment==='cash'?'Наличными':'Картой')+' · '+(o.paymentStatus==='paid'?'Оплачен':'Не оплачен'),o.comment?'Комментарий: '+o.comment:''].filter(Boolean).join('\n').slice(0,4000);}
async function flushNotifications(){
 if(!notificationsConfigured())return;
 const now=Date.now();
 // A lost response may still mean Telegram delivered the message. Never blindly resend it.
 await rt().DB.prepare("UPDATE records SET data=json_set(data,'$.status','uncertain') WHERE kind='notification' AND json_extract(data,'$.status')='sending' AND json_extract(data,'$.leaseUntil')<?").bind(now).run();
 const rows=await rt().DB.prepare("SELECT id,data FROM records WHERE kind='notification' AND json_extract(data,'$.status')='pending' AND COALESCE(json_extract(data,'$.nextTry'),0)<=? ORDER BY created LIMIT 3").bind(now).all<{id:string,data:string}>();
 for(const row of rows.results){const n=JSON.parse(row.data),lease=crypto.randomUUID(),claimed={...n,status:'sending',attempts:(n.attempts||0)+1,lease,leaseUntil:Date.now()+60000};
 const claim=await rt().DB.prepare('UPDATE records SET data=? WHERE id=? AND data=?').bind(JSON.stringify(claimed),row.id,row.data).run();if(!claim.meta.changes)continue;
 let result:any={...claimed,status:'uncertain'};
 try{const o=await read(n.orderId);if(!o)throw Error('missing order');const response=await fetch('https://api.telegram.org/bot'+rt().TELEGRAM_BOT_TOKEN+'/sendMessage',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({chat_id:rt().TELEGRAM_ORDERS_CHAT_ID,text:notificationText(o,n.orderId)}),signal:AbortSignal.timeout(8000)});const body:any=await response.json();if(body.ok===true&&body.result?.message_id){result={...claimed,status:'sent',messageId:body.result.message_id,sentAt:Date.now()};}else if(body.ok===false){result={...claimed,status:'pending',nextTry:Date.now()+Math.max(Math.min(3600000,30000*2**Math.min(claimed.attempts-1,7)),Number(body.parameters?.retry_after||0)*1000),errorCode:Number(body.error_code||response.status)};}}
 catch{/* Delivery outcome is unknown: retain for manual reconciliation. */}
 await rt().DB.prepare("UPDATE records SET data=? WHERE id=? AND json_extract(data,'$.lease')=?").bind(JSON.stringify(result),row.id,lease).run();
 }
}
// One D1 transaction inserts the order and reserves its stock. Snapshot predicates
// reject changes since validation; the unique attempt token prevents retry decrements.
async function commitOrder(id:string,owner:string,order:any,snapshots:{id:string,data:string,quantity:number,tracked:boolean}[],settingsData:string|null){
 const token=crypto.randomUUID(),created=Date.now(),stored={...order,number:crypto.randomUUID(),commitToken:token};
 const insert=rt().DB.prepare(`INSERT INTO records (id,kind,owner,data,created)
 SELECT ?,?,?,?,? WHERE NOT EXISTS (
 SELECT 1 FROM json_each(?) expected LEFT JOIN records actual
 ON actual.id='product:'||json_extract(expected.value,'$.id') AND actual.kind='product'
 WHERE actual.data IS NULL OR actual.data!=json_extract(expected.value,'$.data'))
 AND COALESCE((SELECT data FROM records WHERE id='settings'),'null')=?
 ON CONFLICT(id) DO NOTHING`).bind(id,'order',owner,JSON.stringify(stored),created,JSON.stringify(snapshots),settingsData??'null');
 const updates=snapshots.filter(p=>p.tracked).map(p=>rt().DB.prepare("UPDATE records SET data=json_set(data,'$.stock',json_extract(data,'$.stock')-?) WHERE id=? AND EXISTS (SELECT 1 FROM records WHERE id=? AND json_extract(data,'$.commitToken')=?)").bind(p.quantity,'product:'+p.id,id,token));
 const notice=rt().DB.prepare("INSERT INTO records(id,kind,owner,data,created) SELECT ?,'notification',?,?,? WHERE EXISTS(SELECT 1 FROM records WHERE id=? AND json_extract(data,'$.commitToken')=?) ON CONFLICT(id) DO NOTHING").bind('notice:'+id,owner,JSON.stringify({orderId:id,status:'pending',attempts:0,nextTry:0}),created,id,token);
 await rt().DB.batch([insert,...updates,notice]);
 const saved=await read(id);if(!saved)return out({error:'Меню или остатки изменились. Обновите данные и повторите заказ.'},409);
 if(notificationsConfigured())waitUntil(flushNotifications());const {commitToken,...result}=saved;return out({id,...result});
}
async function identity(req:Request,settings:{owners:string[],staffBotId?:string}=defaults){
 const raw=req.headers.get('x-telegram-init-data');
 if(raw){try{const p=new URLSearchParams(raw);if(new Set(p.keys()).size!==[...p.keys()].length)return null;const date=Number(p.get('auth_date'));if(!date||Math.abs(Date.now()/1000-date)>3600)return null;const sig=p.get('signature');if(!sig)return null;p.delete('signature');p.delete('hash');p.sort();
 const hex='e7bf03a2fa4602af4580703d88dda5bb59f32ed8b02a56c187fe7d34caed242d';const key=await crypto.subtle.importKey('raw',Uint8Array.from(hex.match(/../g)!,h=>parseInt(h,16)),{name:'Ed25519'},false,['verify']);const encoded=sig.replace(/-/g,'+').replace(/_/g,'/');const bytes=Uint8Array.from(atob(encoded.padEnd(Math.ceil(encoded.length/4)*4,'=')),c=>c.charCodeAt(0));const pairs=[...p].map(([k,v])=>k+'='+v).join('\n');const botIds=[...telegramBotIds,String(settings.staffBotId||'')].filter((v,i,a)=>/^\d+$/.test(v)&&a.indexOf(v)===i);let valid=false;for(const botId of botIds){const data=botId+':WebAppData\n'+pairs;if(await crypto.subtle.verify('Ed25519',key,bytes,new TextEncoder().encode(data))){valid=true;break;}}if(!valid)return null;const u=JSON.parse(p.get('user')||'null');if(!Number.isSafeInteger(u?.id))return null;const id='tg:'+u.id;return{id,owner:telegramOwners.includes(id)||settings.owners.includes(id)};}catch{return null;}}
 const id=req.headers.get('oai-authenticated-user-id'),email=req.headers.get('oai-authenticated-user-email');return id&&email?{id:'oai:'+id,owner:email.toLowerCase()==='bagandovarsen228@gmail.com'}:null;
}
export async function GET(req:Request){try{await applyRequestedOpening();const path=new URL(req.url).pathname.split('/').slice(2).join('/');const s={...defaults,...await read('settings')};
 if(path==='menu'){const products=await catalog();return out({products,categories:categoryMetadata(products),settings:{address:s.address,accepting:s.accepting,deliveryEnabled:s.deliveryEnabled,fee:s.fee,minimum:s.minimum,zone:s.zone}});}
 if(path.startsWith('image/')){const obj=await rt().BUCKET.get(path.slice(6));return obj?new Response(obj.body,{headers:{'Content-Type':obj.httpMetadata?.contentType||'image/jpeg','X-Content-Type-Options':'nosniff'}}):out({error:'Нет изображения'},404);}
 const u=await identity(req,s);if(!u)return out({error:'Откройте панель заново из Telegram.'},401);const staff=u.owner||s.staff.includes(u.id);
 if(path==='service-state'){if(!staff)return out({error:'Нет доступа'},403);return out({accepting:s.accepting,notifications:await notificationState()});}
 if(path==='staff-report'){if(!staff)return out({error:'Нет доступа'},403);try{return out(await staffReport(rt().DB,new URL(req.url).searchParams));}catch(e){return out({error:e instanceof ReportInputError?e.message:'Не удалось загрузить отчёт. Попробуйте ещё раз.'},e instanceof ReportInputError?400:503);}}
 if(path==='me')return out({id:u.id,role:u.owner?'owner':staff?'staff':'customer'});
 if(path==='pos'){if(!staff)return out({error:'Доступ только сотрудникам'},403);const products=await catalog();const todayOrders=await staffReport(rt().DB,new URLSearchParams({kind:'orders',period:'today'}),true);const todayRevenue=await staffReport(rt().DB,new URLSearchParams({kind:'revenue',period:'today'}),true);return out({products,categories:categoryMetadata(products),summary:{orders:(todayOrders.summary as any).count,revenue:(todayRevenue.summary as any).total}});}
 if(path==='manage'){if(!u.owner)return out({error:'Доступ только владельцу'},403);await ensureOfficialProducts();const r=await rt().DB.prepare("SELECT data FROM records WHERE kind='product'").all<{data:string}>();return out({settings:s,products:r.results.map(r=>JSON.parse(r.data)).map(p=>({...p,trackStock:!!p.trackStock,stock:Number.isInteger(p.stock)?p.stock:0}))});}
 if(path==='orders'){const params=new URL(req.url).searchParams,all=params.get('all')==='1';if(all&&!staff)return out({error:'Нет доступа'},403);const limit=all?200:100;let cursor:any=null;if(params.has('before')){try{cursor=JSON.parse(params.get('before')!);}catch{return out({error:'Неверная страница'},400);}if(!Number.isSafeInteger(cursor?.created)||typeof cursor?.id!=='string')return out({error:'Неверная страница'},400);}
 const conditions=["kind='order'"],args:(string|number)[]=[];if(!all){conditions.push('owner=?');args.push(u.id);}if(cursor){if(all){const rank=cursor.status==='Новый'?1:0;conditions.push("((json_extract(data,'$.status')='Новый')<? OR ((json_extract(data,'$.status')='Новый')=? AND (created<? OR (created=? AND id<?))))");args.push(rank,rank,cursor.created,cursor.created,cursor.id);}else{conditions.push('(created<? OR (created=? AND id<?))');args.push(cursor.created,cursor.created,cursor.id);}}const r=await rt().DB.prepare(`SELECT id,data,created,(SELECT json_extract(n.data,'$.status') FROM records n WHERE n.id='notice:'||records.id AND n.kind='notification') AS notificationStatus FROM records WHERE ${conditions.join(' AND ')} ORDER BY ${all?"(json_extract(data,'$.status')='Новый') DESC,":''}created DESC,id DESC LIMIT ?`).bind(...args,limit).all<{id:string,data:string,created:number,notificationStatus:string}>();return out(r.results.map(r=>({id:r.id,...JSON.parse(r.data),commitToken:undefined,notificationStatus:all?r.notificationStatus:undefined,created:r.created})));}return out({error:'Не найдено'},404);
 }catch{return out({error:'Сервис временно недоступен. Попробуйте ещё раз.'},503);}}
export async function POST(req:Request){try{await applyRequestedOpening();if(req.headers.get('origin')&&req.headers.get('origin')!==new URL(req.url).origin)return out({error:'Нет доступа'},403);const path=new URL(req.url).pathname.split('/').slice(2).join('/');if(path==='notifications/tick'){if(!rt().NOTIFICATION_JOB_SECRET||req.headers.get('authorization')!=='Bearer '+rt().NOTIFICATION_JOB_SECRET)return out({error:'Нет доступа'},403);await flushNotifications();return out(await notificationState());}const s={...defaults,...await read('settings')};const u=await identity(req,s);if(!u)return out({error:'Откройте панель заново из Telegram.'},401);
 if(path==='upload'){if(!u.owner)return out({error:'Нет доступа'},403);const form=await req.formData(),f=form.get('file');if(!(f instanceof File)||f.size>5000000||!['image/jpeg','image/png','image/webp'].includes(f.type))return out({error:'Выберите JPG, PNG или WebP до 5 МБ'},400);const id=crypto.randomUUID();await rt().BUCKET.put(id,await f.arrayBuffer(),{httpMetadata:{contentType:f.type}});return out({url:'/api/image/'+id});}
 const raw=await req.text();if(raw.length>30000)return out({error:'Слишком большой запрос'},413);let b:any;try{b=JSON.parse(raw);}catch{return out({error:'Некорректный запрос'},400);}if(!b||typeof b!=='object'||Array.isArray(b))return out({error:'Некорректный запрос'},400);
 if(path==='notifications/retry'){if(!u.owner&&!s.staff.includes(u.id))return out({error:'Нет доступа'},403);if(b.confirmUncertain===true&&typeof b.orderId==='string'){await rt().DB.prepare("UPDATE records SET data=json_set(data,'$.status','pending','$.nextTry',0) WHERE id=? AND kind='notification' AND json_extract(data,'$.status')='uncertain'").bind('notice:'+b.orderId).run();}await flushNotifications();return out(await notificationState());}
 if(path==='orders-state'){if(!u.owner&&!s.staff.includes(u.id))return out({error:'Нет доступа'},403);if(!Array.isArray(b.ids)||b.ids.length>200||b.ids.some((id:any)=>typeof id!=='string'||id.length>250))return out({error:'Некорректные заказы'},400);const rows=await rt().DB.prepare("SELECT id,data,created,(SELECT json_extract(n.data,'$.status') FROM records n WHERE n.id='notice:'||records.id) AS notificationStatus FROM records WHERE kind='order' AND id IN (SELECT value FROM json_each(?))").bind(JSON.stringify(b.ids)).all<{id:string,data:string,created:number,notificationStatus:string}>();return out(rows.results.map(r=>({id:r.id,...JSON.parse(r.data),created:r.created,notificationStatus:r.notificationStatus,commitToken:undefined})));}
 if(path==='accepting'){if(!u.owner&&!s.staff.includes(u.id))return out({error:'Нет доступа'},403);if(typeof b.accepting!=='boolean')return out({error:'Некорректное состояние'},400);await rt().DB.prepare("INSERT INTO records(id,kind,owner,data,created) VALUES('settings','settings',?,?,?) ON CONFLICT(id) DO UPDATE SET data=json_set(records.data,'$.accepting',json(CASE WHEN json_extract(excluded.data,'$.accepting') THEN 'true' ELSE 'false' END))").bind(u.id,JSON.stringify({...defaults,accepting:b.accepting}),Date.now()).run();return out({accepting:b.accepting});}
 if(path==='settings'){if(!u.owner)return out({error:'Нет доступа'},403);if(typeof b.accepting!=='boolean'||typeof b.deliveryEnabled!=='boolean'||!Number.isInteger(b.fee)||b.fee<0||!Number.isInteger(b.minimum)||b.minimum<0||!Array.isArray(b.staff)||b.staff.some((x:unknown)=>typeof x!=='string'||!/^tg:\d+$/.test(x))||(b.owners!==undefined&&(!Array.isArray(b.owners)||b.owners.some((x:unknown)=>typeof x!=='string'||!/^tg:\d+$/.test(x))))||(b.staffBotId!==undefined&&b.staffBotId!==''&&!/^\d{6,20}$/.test(String(b.staffBotId))))return out({error:'Проверьте настройки'},400);if(b.deliveryEnabled&&!String(b.zone||'').trim())return out({error:'Укажите зону доставки'},400);await rt().DB.prepare("INSERT INTO records(id,kind,owner,data,created) VALUES('settings','settings',?,?,?) ON CONFLICT(id) DO UPDATE SET data=json_set(excluded.data,'$.accepting',json(CASE WHEN json_extract(records.data,'$.accepting') THEN 'true' ELSE 'false' END))").bind(u.id,JSON.stringify({...defaults,...b,accepting:s.accepting,staffBotId:String(b.staffBotId||''),owners:Array.isArray(b.owners)?b.owners:s.owners,address:String(b.address).slice(0,300),zone:String(b.zone).slice(0,500)}),Date.now()).run();return out({ok:true});}
 if(path==='product'){if(!u.owner)return out({error:'Нет доступа'},403);if(typeof b.name!=='string'||!b.name.trim()||!Number.isInteger(b.price)||b.price<1||b.price>100000||typeof b.cat!=='string'||!b.cat.trim()||!Number.isInteger(b.stock)||b.stock<0||b.stock>100000)return out({error:'Проверьте название, категорию, цену и остаток'},400);const id=b.id||crypto.randomUUID();if(typeof id!=='string'||id.length>150)return out({error:'Некорректное блюдо'},400);const previous=await rt().DB.prepare("SELECT data FROM records WHERE id=? AND kind='product'").bind('product:'+id).first<{data:string}>();if(previous&&b.expectedStock!==undefined&&JSON.parse(previous.data).stock!==b.expectedStock)return out({error:'Остаток изменился. Откройте блюдо заново перед сохранением.'},409);const p={id,name:String(b.name).slice(0,120),desc:String(b.desc||'').slice(0,500),price:b.price,unit:String(b.unit||'').slice(0,50),cat:String(b.cat).slice(0,80),image:typeof b.image==='string'&&/^\/(?!\/)[^\s<>\"\\]*$/.test(b.image)?b.image:'',hidden:!!b.hidden,available:b.available!==false,trackStock:!!b.trackStock,stock:b.stock};if(previous){const saved=await rt().DB.prepare('UPDATE records SET data=? WHERE id=? AND data=?').bind(JSON.stringify(p),'product:'+id,previous.data).run();if(!saved.meta.changes)return out({error:'Блюдо изменилось. Откройте его заново.'},409);}else{await rt().DB.prepare('INSERT INTO records (id,kind,owner,data,created) VALUES (?,?,?,?,?)').bind('product:'+id,'product',u.id,JSON.stringify(p),Date.now()).run();}return out(p);}
 if(path==='stock'){if(!u.owner)return out({error:'Нет доступа'},403);const hasStock=b.stock!==undefined,hasTracking=b.trackStock!==undefined,hasAvailable=b.available!==undefined;if(typeof b.id!=='string'||!hasStock&&!hasTracking&&!hasAvailable||hasStock&&(!Number.isInteger(b.stock)||b.stock<0||b.stock>100000)||hasTracking&&typeof b.trackStock!=='boolean'||hasAvailable&&typeof b.available!=='boolean')return out({error:'Проверьте значение остатка'},400);const row=await rt().DB.prepare("SELECT data FROM records WHERE id=? AND kind='product'").bind('product:'+b.id).first<{data:string}>();if(!row)return out({error:'Блюдо не найдено'},404);const p=JSON.parse(row.data);
 if(hasStock&&b.expectedStock!==undefined&&b.expectedStock!==p.stock)return out({error:'Остаток уже изменился. Обновите список и повторите.'},409);
 if(hasStock)p.stock=b.stock;if(hasTracking)p.trackStock=b.trackStock;if(hasAvailable)p.available=b.available;if(hasStock&&b.trackStock===undefined)p.trackStock=true;
 const saved=await rt().DB.prepare('UPDATE records SET data=? WHERE id=? AND data=?').bind(JSON.stringify(p),'product:'+p.id,row.data).run();if(!saved.meta.changes)return out({error:'Данные изменились. Обновите список и повторите.'},409);return out(p);}

 if(path==='process'){if(!u.owner&&!s.staff.includes(u.id))return out({error:'Нет доступа'},403);const o=await read(b.id);if(!o||!['Новый','Обработан'].includes(o.status))return out({error:'Заказ не найден'},404);await rt().DB.prepare("UPDATE records SET data=json_set(data,'$.status','Обработан','$.processedAt',?) WHERE id=? AND kind='order' AND json_extract(data,'$.status')='Новый'").bind(Date.now(),b.id).run();return out({ok:true});}
 if(path==='payment'){if(!u.owner&&!s.staff.includes(u.id))return out({error:'Нет доступа'},403);if(typeof b.id!=='string'||!['cash','card'].includes(b.payment))return out({error:'Проверьте оплату'},400);const o=await read(b.id);if(!o||!Array.isArray(o.items)||o.status==='Отменён')return out({error:'Заказ недоступен'},404);await rt().DB.prepare("UPDATE records SET data=json_set(data,'$.paymentStatus','paid','$.paidAt',?,'$.paidBy',?,'$.payment',?) WHERE id=? AND kind='order' AND COALESCE(json_extract(data,'$.paymentStatus'),'unpaid')!='paid'").bind(Date.now(),u.id,b.payment,b.id).run();return out({ok:true});}
 if(path==='pos-order'){const isStaff=u.owner||s.staff.includes(u.id);if(!isStaff)return out({error:'Доступ только сотрудникам'},403);if(!/^[\w-]{20,80}$/.test(b.key||'')||!Array.isArray(b.items)||!b.items.length||b.items.length>50||!['card','cash'].includes(b.payment))return out({error:'Проверьте заказ'},400);const id='pos:'+u.id+':'+b.key,old=await read(id);if(old){const {commitToken,...saved}=old;return out({id,...saved});}if(new Set(b.items.map((i:any)=>i?.id)).size!==b.items.length)return out({error:'Блюдо повторяется в заказе'},400);const snapshots:{id:string,data:string,quantity:number,tracked:boolean}[]=[];const settingsData=await rt().DB.prepare("SELECT data FROM records WHERE id='settings'").first<{data:string}>();if(JSON.stringify({...defaults,...(settingsData?JSON.parse(settingsData.data):{})})!==JSON.stringify(s))return out({error:'Настройки изменились. Повторите заказ.'},409);const items=[];for(const i of b.items){if(!i||typeof i.id!=='string'||!Number.isInteger(i.quantity)||i.quantity<1||i.quantity>50)return out({error:'Проверьте количество'},400);const record=await rt().DB.prepare("SELECT data FROM records WHERE id=? AND kind='product'").bind('product:'+i.id).first<{data:string}>();const p=record?JSON.parse(record.data):null;if(!p||p.hidden||!p.available||(p.trackStock&&(!Number.isInteger(p.stock)||p.stock<i.quantity)))return out({error:'Одного из блюд недостаточно в наличии. Обновите кассу.'},409);snapshots.push({id:p.id,data:record!.data,quantity:i.quantity,tracked:!!p.trackStock});items.push({id:p.id,name:p.name,price:p.price,quantity:i.quantity,trackStock:!!p.trackStock});}const total=items.reduce((sum,p)=>sum+p.price*p.quantity,0);const o={items:items.map(item=>({id:item.id,name:item.name,price:item.price,quantity:item.quantity})),total,name:'Заказ у кассы',phone:'',address:'Кафе',delivery:'counter',payment:b.payment,comment:String(b.comment||'').slice(0,500),status:'Обработан',paymentStatus:'unpaid',source:'counter',createdBy:u.id};return await commitOrder(id,u.id,o,snapshots,settingsData?.data??null);}
 if(path==='orders'){if(!/^[\w-]{20,80}$/.test(b.key||''))return out({error:'Некорректный запрос'},400);const id='order:'+u.id+':'+b.key,old=await read(id);if(old){const {commitToken,...saved}=old;return out({id,...saved});}if(!s.accepting)return out({error:'Приём заказов временно остановлен'},409);if(!Array.isArray(b.items)||!b.items.length||b.items.length>50||!['delivery','pickup'].includes(b.delivery)||!['card','cash'].includes(b.payment)||typeof b.name!=='string'||!b.name.trim()||typeof b.phone!=='string'||b.phone.replace(/\D/g,'').length<10)return out({error:'Проверьте заказ и контактные данные'},400);
 if(new Set(b.items.map((i:any)=>i?.id)).size!==b.items.length)return out({error:'Блюдо повторяется в заказе'},400);const snapshots:{id:string,data:string,quantity:number,tracked:boolean}[]=[];const settingsData=await rt().DB.prepare("SELECT data FROM records WHERE id='settings'").first<{data:string}>();if(JSON.stringify({...defaults,...(settingsData?JSON.parse(settingsData.data):{})})!==JSON.stringify(s))return out({error:'Настройки изменились. Повторите заказ.'},409);const items=[];for(const i of b.items){if(!i||typeof i.id!=='string'||!Number.isInteger(i.quantity)||i.quantity<1||i.quantity>20)return out({error:'Проверьте количество'},400);const record=await rt().DB.prepare("SELECT data FROM records WHERE id=? AND kind='product'").bind('product:'+i.id).first<{data:string}>();const p=record?JSON.parse(record.data):null;if(!p||p.hidden||!p.available||(p.trackStock&&(!Number.isInteger(p.stock)||p.stock<i.quantity)))return out({error:'Одного из блюд недостаточно в наличии. Обновите корзину.'},409);snapshots.push({id:p.id,data:record!.data,quantity:i.quantity,tracked:!!p.trackStock});items.push({id:p.id,name:p.name,price:p.price,quantity:i.quantity,trackStock:!!p.trackStock});}const subtotal=items.reduce((v,p)=>v+p.price*p.quantity,0);const destination=deliveryFields(b);if(Object.keys(destination.fields).length)return out({error:'Заполните адрес доставки',fields:destination.fields},400);if(b.delivery==='delivery'&&(!s.deliveryEnabled||subtotal<s.minimum))return out({error:'Проверьте адрес и условия доставки'},400);const o={items:items.map(item=>({id:item.id,name:item.name,price:item.price,quantity:item.quantity})),total:subtotal+(b.delivery==='delivery'?s.fee:0),name:b.name.slice(0,100),phone:b.phone.slice(0,40),address:b.delivery==='pickup'?s.address:destination.address,deliveryDetails:destination.details,source:'miniapp',delivery:b.delivery,payment:b.payment,comment:String(b.comment||'').slice(0,1000),status:'Новый',paymentStatus:'unpaid'};
 return await commitOrder(id,u.id,o,snapshots,settingsData?.data??null);}
 return out({error:'Не найдено'},404);
 }catch{return out({error:'Не удалось сохранить. Попробуйте ещё раз.'},503);}}
